name: Action workflow
on: [push]
jobs:
  git-checkout:
   runs-on: ubuntu-22.04
   steps:
     - name: Git git-checkout
       uses: actions/checkout@v3
     - name: Check Direct Files
       run: ls -a

  get-directory-contents:
   runs-on: ubuntu-latest
   needs: ['git-checkout']
   steps:
     - name: Check Latest Files
       run: ls -a